group :test do
  gem "rspec"
  gem "rspec-rails"
  gem "rspec-mocks"
  gem "rspec-expectations"
  gem "pry"
  gem 'pry-rescue'#, git: "https://github.com/joallard/pry-rescue.git"
  gem 'pry-stack_explorer'
  gem "factory_girl_rails"
  gem 'shoulda'
  gem 'shoulda-matchers'
  gem 'rspec-its'
  gem 'rspec-collection_matchers'
  gem 'database_cleaner', git: "https://github.com/DatabaseCleaner/database_cleaner.git"
  gem 'capybara'
  gem 'selenium-webdriver'
  gem "poltergeist"
end
